# Use the README file as a reference to customize settings.

Book:
  fields:
    default: title, description, category_id
    form: title, description, category_id
  relationships: chapters, taggings, base_tags, tag_taggings, tags, category
  application: Application
