# Use the README file as a reference to customize settings.

Chapter:
  fields:
    default: content, number, book_id, title
    form: content, number, book_id, title
  relationships: 
  application: Application
